### ISSUE TITLE
Inconsistent types

### ISSUE THREAD

**Issue by oded-dd** [arianvp/dhall-kubernetes#76] opened 2019-08-03 16:41 UTC
The current `dhall-kubernetes` does not give a generic way for the `object` type of `kubernetes` E.g.  configMap.core.v1.data which is of type object under the kubernetes API documentation is translated to ``` data : List { mapKey : Text, mapValue : Text } ``` which does not support nested map Values (https://github.com/dhall-lang/dhall-kubernetes/blob/master/types/io.k8s.api.core.v1.ConfigMap.dhall)

`dhall 9` now supports weakly-typed JSON (#586) which should solve the issue. Is there a plan to support it?

**Comment by arianvp** [comment] 2019-08-04 13:03
Thanks for raising this issue.

I think This is a duplicate of https://github.com/dhall-lang/dhall-kubernetes/issues/74

I think weakly typed JSON for object types is indeed the way to go .

**Closed as completed** 2019-08-04 13:04 UTC
